README.md
client-auth/README.md

feat: adds client id spec

---

chat/data-structures.md

As triaged during Chat SDK sync

fix(data-structures): adds missing `publicKey` on `Invite`

---

auth/rpc-methods.md
chat/chat-keyserver.md
chat/invite-uri.md
chat/rpc-methods.md
relay/client-auth.md
relay/relay-server.md
sign/pairing-uri.md
sign/rpc-methods.md

rename iridium to irn

---

sign/data-structures.md
sign/rpc-methods.md

Related to: https://github.com/WalletConnect/walletconnect-specs/issues/95

add optional deep link field to controller meta data

---

auth/client-api.md

As discussed on yesterday's sdk meeting.

Update Auth client-api.md

---

auth/authentication.md

- Clarify using new response topic but same pairing topic for existing pairing
flow

Clarify response topic flow for existing pairing

---

docs/specs/servers/keys/identity-keys.md

fix: emoji

---

docs/specs/servers/keys/keys-server-api.md

Wrap with the status response, just like failure response.

fix: success response

---

docs/specs/servers/keys/identity-keys.md

See: https://github.com/WalletConnect/WalletConnectRust/issues/42

fix: necessary extra newline

---

docs/specs/servers/notify/notify-server-api.md

Follow up on https://github.com/WalletConnect/cloud-app/pull/647

chore(rename-notify-secret): rename Notify API secret

---

docs/specs/clients/notify/rpc-methods.md

Paired with [this Notify Server PR](https://github.com/WalletConnect/notify-server/pull/157).

fix: app is also updated

---

docs/specs/clients/core/identity/identity-keys.md

Separate link for all apps to enable easier explanation: https://www.notion.so/walletconnect/Notification-authorization-info-pages-00dd571ab01a47df86e674d67ac10fe7?pvs=4

feat: separate all apps link

---

docs/specs/meta-clients/web3modal/api.md

Follow up PR to:
- https://github.com/WalletConnect/api-web3modal/pull/43#issue-2107190000

chore(web3modal-api): add chains filter param

---

docs/specs/servers/blockchain/blockchain-server-api.md

This PR adds specifications for the Account Balances request and response to the Blockchain-API service.

feat(blockchain-api): account balances

---

docs/specs/servers/blockchain/blockchain-server-api.md

This PR adds specifications for the SWAP request and response to the Blockchain-API service.
Requirements:
* It must support gasless/aproveless transactions [EIP-2612](https://eips.ethereum.org/EIPS/eip-2612).
* Should be vendor-agnostic
* It should support x-chain swap
* It should be open for an extension (for the x-chain swaps) but not for the modification.
The following endpoints are added:

feat(blockchain-api): SWAP endpoints

---

docs/specs/servers/blockchain/blockchain-server-api.md

This PR adds a gas price endpoint that is required for the UX for the conversion feature.

feat(blockchain-api): gas price endpoint

---

docs/specs/servers/blockchain/blockchain-server-api.md
docs/specs/servers/notify/notify-server-api.md
docs/specs/servers/relay/relay-server-rpc.md

fix: typos

---

docs/specs/servers/blockchain/blockchain-server-api.md

This PR adds API specifications for the conversion allowance.

feat(blockchain-api): conversion allowance endpoint

---

docs/specs/servers/blockchain/blockchain-server-api.md

This PR updates the Blockchain-API balance endpoint with the ability to force the update of the balance for the specific token using it's contract address to eliminate the balance cache and make UX better.

feat(blockchain-api): force balance update for the specific fungible

---

docs/specs/servers/blockchain/blockchain-api.md

This PR adds the Blockchain-API history endpoint API description to the documentation.

fix(blockchainAPI): adding history endpoint API
