chat/client-api.md, chat/rpc-methods.md
- Aligns `chat_message` payload with the defined `Message` data type, i.e. incoming argument should be `Message` not a plain `string`
- Renames argument key from `message` to `payload` to avoid the syntactically awkward `message.message`
=> fix: `chat_message` event payload type

docs/specs/clients/notify/README.md, docs/specs/clients/notify/client-api.md, docs/specs/clients/notify/dapp-authentication.md, docs/specs/clients/notify/data-structures.md, docs/specs/clients/notify/error-codes.md, docs/specs/clients/notify/notify-authentication.md, docs/specs/clients/notify/notify-notification-types.md, docs/specs/clients/notify/notify-subscription.md, docs/specs/clients/notify/rpc-methods.md, docs/specs/clients/notify/spam-protection.md, docs/specs/clients/notify/usage-of-history-api.md, docs/specs/clients/notify/usage-of-sync-api.md, docs/specs/servers/notify/notify-server-api.md
- Move the notify specs from walletconnect-docs repo.
- Pull changes from https://github.com/WalletConnect/walletconnect-docs/pull/859
- Made further fixes and improvements to:
- notify-server-api.md
- notify-authentication.md
- dapp-authentication.md
=> feat: notify specs

docs/specs/clients/notify/notify-authentication.md, docs/specs/clients/notify/rpc-methods.md
Update notify message TTLs as per discussion today.
- JWT and message TTLs are equal
- How to handle race condition between JWT and message TTLs
- All responses (subscription response, subscription update response, subscription delete response, notify receipt) have 30 day TTLs to make sure the other side is able to receive them
- Message TTL remains 30 days to ensure the client receives it
- Subscription delete request TTL increased to 30 days to ensure notify server receives it (subscription expires after 30 days anyway), even if device submits it optimistically
- Subscription request and subscription update request TTLs reduced to 30 seconds to avoid unexpected changes with a subscription being created or updated days after the client submitted it
=> feat: update TTLs

docs/specs/servers/keys/identity-keys.md
This should match the domain from `aud` and all of the other examples.
=> fix: domain

docs/specs/clients/core/identity/identity-keys.md, docs/specs/clients/notify/authentication.md, docs/specs/clients/notify/client-sdk-api.md
Removes the concept of limited domain-specific access as per [this discussion](https://walletconnect.slack.com/archives/C044SKFKELR/p1695563295242719?thread_ts=1695562072.395209&cid=C044SKFKELR).
Adds `app` field to `wc_notifyWatchSubscriptions` request to enable Notify Server to discern which domain is to be watched because `domain` field of SIWE message is no longer used. (This is a performance benefit.)
=> feat: remove limited access

docs/specs/clients/notify/notify-config.md
Introduces a new `id` field for notification types which allows `name` to be human-readable.
`id` must contain only lowercase letters, numbers, hyphens, or underscores. This allows our existing set of notifications (`gm_hourly`), as well as auto-incrementing number and uuid IDs.
Context: https://walletconnect.slack.com/archives/C044SKFKELR/p1696459959133769
=> feat: cloud notification config & notification type IDs

docs/specs/clients/core/identity/identity-keys.md, docs/specs/clients/notify/authentication.md, docs/specs/clients/notify/client-sdk-api.md
Adds back limited access without using DAPP or WALLET terminology. This strikes a good balance between maximum flexibility and per-dapp security. Context: https://walletconnect.slack.com/archives/C044SKFKELR/p1696849588571799
Note that [`app` field for notifyWatchSubscriptions](https://github.com/WalletConnect/walletconnect-specs/pull/149) still exists.
Added to Notify Server in this PR: https://github.com/WalletConnect/notify-server/pull/123
=> feat: add back limited access

docs/specs/clients/notify/rpc-methods.md
Clarifies behavior when notifyWatchSubscriptions is called multiple times. Currently, Notify Server will create a new watcher for each call, but the desired behavior involves updating the watcher instead.
=> feat: notifyWatchSubscriptions refresh updates

docs/specs/clients/notify/data-structures.md
This makes the `url` and `icon` fields nullable. Clients should have fallback behavior e.g. no click behavior and no icon.
=> feat: nullable url and icon

docs/specs/clients/notify/data-structures.md
We have to revert this as this is a breaking change on older clients. Since Notify should no longer have too many braking changes we cannot make this change anymore
=> Make icon and url not nullable again

docs/specs/clients/notify/client-sdk-api.md
Remove Push Server from register/unregister methods as clients implement this elsewhere.
Also improve register method description.
=> chore: remove Push Server registration

docs/specs/clients/core/identity/identity-keys.md
"Identity" is not intuitive for a user. Updating to account. Context: https://walletconnect.slack.com/archives/C044SKFKELR/p1698242303262989?thread_ts=1698155560.705779&cid=C044SKFKELR
Redirect endpoint added [here](https://github.com/WalletConnect/www-walletconnect/pull/118).
=> feat: update statement

docs/specs/meta-clients/web3modal/api.md
- These static ID mappings are currently buried in the [Web3Modal web implementation](https://github.com/WalletConnect/web3modal/blob/V3/packages/scaffold-utils/src/PresetsUtil.ts), but should be surfaced for devs implementing Web3Modal UIs
=> chore: specifies known static assetIds for networks and connectors

docs/specs/clients/notify/authentication.md, docs/specs/clients/notify/rpc-methods.md
- Adds `sbs` which is the list of subscriptions to `notifySubscribe`, `notifyUpdate`, and `notifyDelete` responses to simplify client-side implementation to avoid listening for an additional subscriptionsChanged. [Context](https://walletconnect.slack.com/archives/C044SKFKELR/p1701870285066439?thread_ts=1701804693.064159&cid=C044SKFKELR).
- Adds `mjv` to all JWTs which enables each side to tell what version the other side is using and if there have been any major breaking changes to the API in-use.
- Notify Server can use this to tell if a client supports the new `sbs` response field and thus will avoid sending a duplicate subscriptionsChanged request to supporting clients
- Clients can use this to tell if Notify Server has broken support for an old API version, and for clients to fail …
=> feat: subs in subscribe response & versioning information

docs/blockchain-rpc/hedera-rpc.md
This PR fixes some inconsistency errors and typos on the Hedera spec page. This does **not** change the spec
=> Hedera - fix formatting and typos / errors in examples

docs/specs/clients/notify/client-sdk-api.md, docs/specs/clients/notify/data-structures.md
- Add imageUrls to scopes as we want to use images from notification types, nor from the `icon` property of notifications
- Add `id` and `name` since they are already implemented
=> Add image urls scopes

docs/specs/servers/blockchain/blockchain-server-api.md
This PR introduces the SPEC for the new blockchain-api endpoint for the Coinbase On Ramp Pay SDK URL generator.
* New proposed endpoint: `/v1/generators/onrampurl`
* Input parameters are according to the [generateOnRampURL](https://docs.cloud.coinbase.com/pay-sdk/docs/generating-url#generateonrampurl-parameters) serialized in JSON and using the `POST` method.
The implementation in the blockchain-api: https://github.com/WalletConnect/blockchain-api/pull/453
=> feat: onramp pay sdk URL generator spec

docs/specs/clients/core/crypto/crypto-envelopes.md
Newlines were ignored because it's markdown. Wrapping in code block so easier to read.
=> fix: newline formatting

docs/specs/servers/blockchain/blockchain-server-api.md
Registering hexless account name and updating it.
Adding and updating addresses for the name.
=> feat: hexless account profiles register and update RPC specs

docs/specs/clients/notify/client-sdk-api.md, docs/specs/clients/notify/data-structures.md
- remove `getUnreadCount` as it would be redundant since we should supply in read count in get subscriptions call 
- simplify `notificiations_changed_event` so it can be easily used for diffing state cached by the client or user of the sdk
- add `unreadCount` to subscriptions
- Remove `getNotification` as it would be redundant. If someone wanted to display details of a selected notification, they can retrieve it from the existing list of notifications
=> chore: update to a desirable client api

docs/specs/servers/blockchain/blockchain-server-api.md
This PR adds the specification for updating the hexless account name attributes to give user the ability to update attributes after the name registration.
To authorize the name ownership we will use the same as in the name registration signed message with payload.
The recovered address will be compared to the address from the name entity to check the legitimate owner update.
=> feat(ens): updating name attributes

docs/specs/servers/blockchain/blockchain-server-api.md
This PR changes the ENS Gateway lookup responses to the [ENSIP-11](https://alpha-docs.ens.domains/ensip/11) compatible according to the ENS discussion. This should make it easier to hook everything up on the smart contract side.
The new lookup response will look like this:
```
{
"name": "maxim.connect.id",
"registered_at": "2024-01-23T18:50:02.083933Z",
"updated_at": "2024-01-23T18:50:02.083933Z",
"attributes": {
"bio": "im a test"
},
"addresses": {
"60": { // SLIP-44 and ENSIP-11 compatible coin type. 60 - Ethereum Mainnet
"address": "0xAff392551773CCb2574fAE23195CC3aFDBe98d18",
"created_at": "2024-01-23T18:50:02.083933Z"
}
}
}
```
The gateway implementation: [#489](https://github.com/WalletConnect/blockchain-api/pull/489)
=> feat(ens): using the ENSIP-11 compatible lookup responses

docs/specs/servers/blockchain/blockchain-server-api.md
This PR adds the specification for updating the hexless account name address to give users the ability to update addresses after the name registration.
To authorize the name ownership we will use the same technique as in the name registration signed message with payload.
The recovered address will be compared to the address from the name entity to check the legitimate owner update.
=> feat(ens): name address update

docs/specs/servers/blockchain/blockchain-server-api.md
This PR making the following changes:
* Adding missed `projectId` to the required query arguments for the account balances API,
* Available options for the `currency` and `chainId` were added,
* Description of `HTTP 202` response was added.
=> fix(balances): adding `projectId` to the query parameters and available options

docs/specs/clients/sign/namespaces.md, docs/specs/meta-clients/web3modal/api.md
* The CAIP-2 standard for Solana was fixed after-the-fact to contain the correct genesis hashes for each chain: https://github.com/ChainAgnostic/namespaces/blob/main/solana%2Fcaip2.md#test-cases
* Our documentation and sample code references need to be adjusted to the canonical hashes/chainIds.
=> fix: update Solana CAIP-2 chainId reference

docs/specs/servers/blockchain/blockchain-server-api.md
This PR adds a missed token address in the `blockchain-api` balance endpoint.
=> fix(balances): adding missed token address in balance endpoint

docs/specs/servers/blockchain/blockchain-server-api.md
This PR fixing typos and style correcting:
* Corrects the wrong CAIP,
* Making all capitals in lists in the blockchain-API specs.
=> fix(blockchain-api): correct CAIP links and capitals in the list

docs/specs/servers/blockchain/blockchain-server-api.md
This PR adds to the docs current Blockchain-API Identity (ENS) `address->name` lookup endpoint.
=> feat(blockchain-api): adding identity lookup blockchain-api

docs/specs/clients/notify/client-sdk-api.md
Recaps support has been in the notify SDKs for a while but we have not officially specced it out yet.
Here's the spec, mimicking the current implementation on JS.
=> chore: add prepare registration with recaps spec

docs/specs/clients/sign/rpc-methods.md
This PR introduces rejection tags for session proposals and authenticated session flow to include them in the connection flow success rate metric calculations.
Currently, there's no way to see rejection from the data POV, this PR enables it.
=> feat: rejection tags

docs/specs/servers/blockchain/blockchain-server-api.md
This PR makes `amount` optional in the conversion approval endpoint to allow infinite amounts to be approved.
=> fix(blockchain-api): making amount optional in conversion approval

docs/specs/servers/blockchain/blockchain-server-api.md
This PR adds an optional `gasPrice` parameter to the conversion quote endpoint to allow the user to choose the gas type (normal, fast, etc.)
=> feat: adding `gasPrice` optional parameter to the convertion quote

docs/specs/servers/blockchain/blockchain-server-api.md
This is a proposal for the fungible price endpoint SPEC for the Blockchain-API.
The new endpoint `/v1/fungibles/price` should respond with the price of the fungible asset calculated in the requested currency. 
The fungible assets are filtered by the CAIP-10 implementation address.
=> feat(blockchain-api): fungible price endpoint

docs/specs/servers/blockchain/blockchain-server-api.md
This PR adds a description to the name suggestion endpoint in Blockchain-API.
* Description for the query parameters was added,
* Description for the returning object was added.
=> fix(blockchain-api): parameters description for names suggestions

docs/specs/servers/blockchain/blockchain-api.md
This PR updates the SPEC description according to the [#669](https://github.com/WalletConnect/blockchain-api/pull/669) changes: adding mainnet cointype by default if non-mainnet cointype provided during the registration.
=> feat(names): updating name registration spec to add mainnet by default

docs/specs/servers/blockchain/blockchain-api.md
This PR adds an optional `apiVersion=2` query parameter for name lookups to fix the [404 response issue](https://github.com/WalletConnect/blockchain-api/issues/700) and support backward compatibility.
=> feat(blockchainAPI): adding `v=2` optional query parameter for name lookups

docs/specs/servers/blockchain/blockchain-bundler-api.md
This PR adds a bundler interaction API to the Blockchain-API new `/v1/bundler` endpoint. The user can choose the bundler to call and pass the json-rpc operation to the designated bundler.
=> feat(blockchainAPI): bundler interaction API

docs/specs/servers/blockchain/blockchain-api.md
This PR adds a missed `x-sdk-version` header requirement for the address balance request to the Blockchain-API.
=> fix(blockchainAPI): adding required `x-sdk-version` header for the balance request

docs/specs/servers/relay/relay-server-rpc.md
As per the [Verify V2](https://www.notion.so/walletconnect/Verify-Server-rewrite-tech-doc-Verify-API-V2-30e207c77f8447d8af37a186799b7c9e?pvs=4#fbc0ca6d67c444118599ba49d8b358f9) technical doc, this adds the `attestation` field to the data the relay relays.
=> feat: verify attestation field

docs/specs/servers/blockchain/blockchain-bundler-api.md
This PR update supported bundler operations for the blockchain API endpoint. The core change is https://github.com/WalletConnect/blockchain-api/pull/761
=> feat(blockchainAPI): extending supported bundler operations

docs/specs/servers/blockchain/blockchain-rpc-api.md
This PR describes the supported chains list endpoint `/v1/supported-chains` in the Blockchain-API.
=> fix(blockchainAPI): adding supported chains list endpoint

docs/specs/servers/blockchain/blockchain-api.md
This PR adds an optional `zone` query parameter to the name suggestion endpoint to support a backward compatibility for the legacy `wcn.id` name. By default the `wcn.id` name zone will be used for the backward compatibility and `zone=x` should be used for the new domain zone.
=> feat(blockchainAPI): adding optional zone query parameter for the name suggestions

docs/specs/servers/blockchain/blockchain-api.md
This PR fixes the Blockchain-API balances filtering parameter name from `chain` to `chainId`.
=> fix(blockchainApi): fixing the balance filtering parameter by chainId

docs/specs/servers/blockchain/blockchain-api.md
This PR adds `decimals` field description to the `/v1/fungible/price` endpoint response.
=> fix(blockchainAPI): adding `decimals` to the fungible price endpoint

docs/specs/servers/blockchain/blockchain-bundler-api.md
This PR updates the blockchain-api bundler operations methods to the up-to-date state and fixes the bundler name parameter.
=> fix(blockchain-api): updating bundler ops methods

docs/specs/servers/blockchain/blockchain-bundler-api.md
This PR extends bundler ops with two new methods according to the [#888](https://github.com/reown-com/blockchain-api/pull/888).
=> feat(blockchain-api): extending bundler ops methods
